dataset: ecl
fixed:
  root_path: ./datasets/
  data_path: ECL.csv
  model_id: ECL
  data: custom
  enc_in: 321
  pred_len: 720
  cycle: 168
  model_type: mlp
seq_len_configs:
  48:
    learning_rate: 0.005
    d_model: 256
  96:
    learning_rate: 0.001
    d_model: 512
  192:
    learning_rate: 0.001
    d_model: 512
  336:
    learning_rate: 0.001
    d_model: 512
  720:
    learning_rate: 0.001
    d_model: 512     