dataset: soil
fixed:
  root_path: ./datasets/
  data_path: DeepSoil.csv
  model_id: DeepSoil
  data: custom
  enc_in: 4
  pred_len: 720
  cycle: 24
  model_type: mlp
seq_len_configs:
  48:
    learning_rate: 0.005
    d_model: 128
  96:
    learning_rate: 0.005
    d_model: 128
  192:
    learning_rate: 0.005
    d_model: 128
  336:
    learning_rate: 0.001
    d_model: 256
  720:
    learning_rate: 0.001
    d_model: 128
