dataset: soil
fixed:
  root_path: ./datasets/
  data_path: DeepSoil.csv
  model_id: DeepSoil
  data: custom
  enc_in: 4
  pred_len: 720
  cycle: 24
  short_type: sin
  long_type: sin
  long_len: 128
seq_len_configs:
  48:
    learning_rate: 0.001
    lradj: type1
    use_norm: 1
    use_pos: 1
    d_model: 128
    d_ff: 256
    e_layers: 1
    N: 0
    short_periods: [24]
    long_periods: [8760]
  96:
    learning_rate: 0.001
    lradj: type1
    use_norm: 1
    use_pos: 1
    d_model: 128
    d_ff: 256
    e_layers: 1
    N: 0
    short_periods: [24]
    long_periods: [8760]
  192:
    learning_rate: 0.001
    lradj: type1
    use_norm: 1
    use_pos: 1
    d_model: 128
    d_ff: 256
    e_layers: 1
    N: 0
    short_periods: [24]
    long_periods: [8760]
  336:
    learning_rate: 0.001
    lradj: type1
    use_norm: 1
    use_pos: 1
    d_model: 128
    d_ff: 256
    e_layers: 1
    N: 0
    short_periods: [24]
    long_periods: [8760]            
  720:
    learning_rate: 0.001
    lradj: type1
    use_norm: 1
    use_pos: 1
    d_model: 128
    d_ff: 256
    e_layers: 1
    N: 0
    short_periods: [24]
    long_periods: [8760]
