dataset: soil
fixed:
  root_path: ./datasets/
  data_path: DeepSoil.csv
  model_id: DeepSoil
  data: custom
  enc_in: 4
  seq_len: 96
pred_len_configs:
  96:
    learning_rate: 0.005
    d_model: 128
    d_ff: 128
    e_layers: 2
  192:
    learning_rate: 0.001
    d_model: 128
    d_ff: 128
    e_layers: 1
  336:
    learning_rate: 0.005
    d_model: 128
    d_ff: 128
    e_layers: 1
  720:
    learning_rate: 0.001
    d_model: 128
    d_ff: 128
    e_layers: 2
