dataset: weather2k
fixed:
  root_path: ./datasets/
  data_path: Weather2K.csv
  model_id: Weather2K
  data: custom
  enc_in: 100
  pred_len: 720
seq_len_configs:
  48:
    learning_rate: 0.001
    d_model: 128
    d_ff: 128
    e_layers: 2
  96:
    learning_rate: 0.001
    d_model: 128
    d_ff: 128
    e_layers: 2
  192:
    learning_rate: 0.001
    d_model: 128
    d_ff: 128
    e_layers: 2
  336:
    learning_rate: 0.001
    d_model: 128
    d_ff: 128
    e_layers: 2
  720:
    learning_rate: 0.001
    d_model: 128
    d_ff: 128
    e_layers: 2
